## Basic Configuration

baseurl = "/" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Jason Lyle Golderg"
title = "Jason Lyle Goldberg"

theme = "hugo-goa"

## Hugo Built-in Features
# disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Jason Lyle Goldberg"
intro = "Published Author, Musician, Seeker"
description = "Recently completed Oh go to the Devil, currently writing Laowai and assorted short fiction."
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Jason Lyle Goldberg the Author and Musician"
keywords = "literature, music, fiction, writer, musician"

## Social Accounts
[params.social]
linkedin = "jlylegoldberg"
twitter = "jlylegoldberg"
facebook = "jlylegoldberg"
email = "goldbergx609@gmail.com"

## Extras
[params.extra]
copyright = "© 2018. Jason Lyle Goldberg. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = true
highlightjs = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
